# Generated by Django 4.2.4 on 2023-08-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id_contato', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.TextField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Telefone', models.TextField(max_length=255)),
            ],
        ),
    ]
